name: Build BluetoothAudioCodecInspector

on:
  workflow_dispatch:  # allows manual trigger in GitHub UI

jobs:
  build:
    name: Build on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore BluetoothAudioCodecInspector.sln

      - name: Build solution (Release)
        run: dotnet build BluetoothAudioCodecInspector.sln -c Release --no-restore

      - name: Upload built .exe
        uses: actions/upload-artifact@v4
        with:
          name: BluetoothAudioCodecInspector
          path: |
            BluetoothAudioCodecInspector\bin\Release\net6.0-windows\*.exe
