name: Build BluetoothAudioCodecInspector

on:
  workflow_dispatch:  # allows manual trigger in GitHub UI

jobs:
  build:
    name: Build on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore BluetoothAudioCodecInspector.sln

      - name: Publish self-contained Win exe
        run: dotnet publish BluetoothAudioCodecInspector.sln -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true


      - name: Upload built executable
        uses: actions/upload-artifact@v4
        with:
          name: BluetoothAudioCodecInspector
          path: |
            **/publish/*.exe

